package com.unicauca.maestria.api.gestiontrabajosgrado.common.enums;

public enum EstadoTrabajoGrado {
    SIN_REGISTRAR_SOLICITUD_EXAMEN_DE_VALORACION,
    PENDIENTE_RESULTADO_EXAMEN_DE_VALORACION,
    EXAMEN_DE_VALORACION_APROBADO,
    EXAMEN_DE_VALORACION_NO_APROBADO,
    EXAMEN_DE_VALORACION_APLAZADO,
    SUSTENTACION_APROBADA,
    SUSTENTACION_NO_APROBADA,
    EXAMEN_DE_VALORACION_FINALIZADO_SIN_EXITO
}
