spring:
  application:
    name: ms-gestion-trabajo-grado
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: ${SPRING_MAIL_SMTP}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
   port: ${SPRING_SERVER_TRABAJO_GRADO_PORT}

app:
  jwtSecret: ${SPRING_JWT_KEY}
  jwtExpirationMs: ${SPRING_JWT_EXPIRATION}