package com.unicauca.maestria.api.gestiontrabajosgrado.common.enums.estudiante;

public enum Discapacidad {

	SITEMA_NERVIOSO,
	OJOS,OIDOS,OLFATO,TACTO,GUSTO,
	CARDIORRESPIRATORIO,
	DEFENSAS,
	DIGESTION,
	METABOLISMO,
	HORMONAS,
	SISTEMA_GENITAL,SISTEMA_URINARIO,SISTEMA_REPRODUCTIVO,
	MANOS,BRAZOS,PIERNAS,
	PIEL,CABELLO,SINDROMES,
	NINGUNO;
}
